### ISSUE TITLE
日进 甲/改 无法选择 零式水中听音机

### ISSUE THREAD

**Issue by KanaHayama** [TeamFleet/WhoCallsTheFleet-DB#15]
零式水中听音机 条目中写着可以装备在日进甲 中。
实际上日进甲和日进改都可以装备。
但在舰队编成中却无法选择这个装备。
因为不知道是在哪个环节出现了问题，不敢贸然更改。

**Comment by Diablohu** [comment]
每个舰娘数据下都有个“不可装备类型”，当时不知道为何给日进改和日进甲勾上了大型声纳

多谢提出，已经修改，随下个版本更新实装
