### ISSUE TITLE
关于使用授权

### ISSUE THREAD

**Issue by Gizeta** [TeamFleet/WhoCallsTheFleet-DB#2]
你好，这里是舰娘百科。我们想在网站上使用大大的数据，不知道有没有什么限制？

**Comment by Diablohu** [comment]
基于MIT许可协议，只需要在你的项目里提出来源即可。如果是开源项目还需要保留MIT协议并在源代码中也提供来源

**Comment by Gizeta** [comment]
嗯。谢谢。
