### ISSUE TITLE
部分初始装备数据丢失？

### ISSUE THREAD

**Issue by sinsinpub** [TeamFleet/WhoCallsTheFleet-DB#25]
如图，貌似近来更新改二之类数据时把原型和改的初始装备也清空了？
![image](https://user-images.githubusercontent.com/160240/116801830-db920000-ab3f-11eb-9db6-071e20631faf.png)
粗略查了一下有这些ID （只排除了可以转换改造的，有些应该是本来就没有初始装备
[607, 231, 94, 400, 402, 163, 15, 500, 499, 636, 642, 587, 155, 493, 16, 665, 230, 93, 367, 530, 495, 232, 637, 407, 605, 494, 602, 162, 334, 314, 483, 128, 147, 535, 697, 539]

另一个小问题，[250] Spitfire Mk.I的改修上Ark Royal有变化，只有周一、二可以了
![image](https://user-images.githubusercontent.com/160240/116802026-1137e880-ab42-11eb-8c33-39c721bfe425.png)
![image](https://user-images.githubusercontent.com/160240/116802015-f2d1ed00-ab41-11eb-9250-1a01062bec5c.png)

**Comment by Diablohu** [comment]
因为我这边的一个 bug，导致最近一次更新中添加限定图鉴时把初始装备清空了
这个问题仅影响更新了限定图鉴的舰娘
其他舰娘，确实没有初始装备

**Comment by sinsinpub** [comment]
人肉对了一下潜艇以外的，还缺这两个的
ID 637
![image](https://user-images.githubusercontent.com/160240/116809878-12cdd480-ab73-11eb-97dd-898f8a8c22c3.png)
ID 642
![image](https://user-images.githubusercontent.com/160240/116809900-2ed17600-ab73-11eb-92f6-75a7d0aaf77a.png)

**Comment by Diablohu** [comment]
fixed https://github.com/TeamFleet/WhoCallsTheFleet-DB/commit/9701eb1c53accf10048fd9324416f85f5479cdb6
