### ISSUE TITLE
两艘新船【梅改】【玉波改】一改可以带大发，希望添加，谢谢

### ISSUE THREAD

**Issue by YuukyuuKikan** [TeamFleet/WhoCallsTheFleet-DB#27]
PR范例看过了，感觉理解起来有些困难，DB Manager的APP不太清楚该用什么编译，只好提issue。

希望增加【梅改】【玉波改】的装备类型包括大发动艇，谢谢

**Comment by Diablohu** [comment]
抱歉这么晚才回复

今晚我会进行一次统一的数据更新，会处理近一个半月来游戏更新的所有新内容

感谢支持

**Comment by Diablohu** [comment]
已更新完毕
