### ISSUE TITLE
 八幡丸（未改）可以装备舰攻系列，冬月（未改）可以装备大电探

### ISSUE THREAD

**Issue by YuukyuuKikan** [TeamFleet/WhoCallsTheFleet-DB#28]
无意中发现的，因为不是最终改造形态所以可以下次一并修复。

**Comment by YuukyuuKikan** [comment]
另外很奇怪的是夜攻似乎被算在数据库里了，大概是因为夜攻和舰攻用的不是同一种装备类型？

总之试着从云鹰词条仿写了"additional_item_types":[19]，就是不太清楚后面的数字代表了什么（来自item_types.nedb？）。所以不太敢PR

**Comment by YuukyuuKikan** [comment]
追加冬月未改可装备大电探。
有空的话我琢磨一下怎么部署提交工具，似乎是依赖nodejs

**Comment by Diablohu** [comment]
已更新到最新版本
迟来的更新还请抱歉

**Comment by YuukyuuKikan** [comment]
关于冬月：
抱歉，是我这里不仔细了。
我对比了秋月级的额外装备之后确定冬月/冬月改与其他秋月级的额外装备内容完全一致，希望添加：
冬月：大电探，司令部（未改冬月司令部待验证，我记得有）
冬月改：大电探，大水听，中PAD，司令部。

**Comment by Diablohu** [comment]
我终于发现问题根源了——手动更新过“冬月”，忘了更新“冬月改” 😨

**Comment by Diablohu** [comment]
数据已更新，会实装在呼叫舰队下次更新中
