### ISSUE TITLE
新装备 5inch连装炮（副炮配置）集中配备 的可装备舰种类不正确

### ISSUE THREAD

**Issue by OrangeMontBlanc** [TeamFleet/WhoCallsTheFleet-DB#29]
![image](https://user-images.githubusercontent.com/62413061/175196126-cb32a288-c883-4268-b760-f44958aa72bb.png)
![image](https://user-images.githubusercontent.com/62413061/175196156-bd67d19b-d514-497a-a1d0-335446421c32.png)

**Comment by Diablohu** [comment]
数据已更新
