### ISSUE TITLE
Incorrect asw_max value for Uzuki Kai

### ISSUE THREAD

**Issue by yoridorimidori** [TeamFleet/WhoCallsTheFleet-DB#3]
From this update
https://twitter.com/KanColle_STAFF/status/748450420452790272

Should be 65 instead of 63
http://wikiwiki.jp/kancolle/?%B1%AC%B7%EE%B2%FE
http://kancolle.wikia.com/wiki/Uzuki

**Comment by yoridorimidori** [comment]
Hamakaze Kai 68 instead of 64
http://wikiwiki.jp/kancolle/?%C9%CD%C9%F7%B2%FE
Isokaze Kai 68 instead of 64
http://wikiwiki.jp/kancolle/?%B0%EB%C9%F7%B2%FE
Tanikaze Kai 69 instead of 68
http://wikiwiki.jp/kancolle/?%C3%AB%C9%F7%B2%FE
Maikaze Kai 68 instead of 64
http://wikiwiki.jp/kancolle/?%C9%F1%C9%F7%B2%FE

**Comment by Diablohu** [comment]
thanks for the info. will update soon
