### ISSUE TITLE
[求教] 请问_id字段与实际数据的关系

### ISSUE THREAD

**Issue by mczoden** [TeamFleet/WhoCallsTheFleet-DB#4]
Hi DiabloHu：

小弟有个问题想请教一下。
db里的每一行json数据中，都有一个_id字段，看上去像是个散列结果，不知是如何生成的，与存储的这条数据本身是否有关系？
还请赐教，谢谢

**Comment by Diablohu** [comment]
NeDB自动生成的内部ID，可以直接无视

**Comment by mczoden** [comment]
懂了，谢谢解答，请关闭Issue
