### ISSUE TITLE
关于 npm 包版本

### ISSUE THREAD

**Issue by KagamiChan** [TeamFleet/WhoCallsTheFleet-DB#5]
Hi，从 8.1 版本开始，poi  加入了 WhoCallsTheFleet-DB，具体的方法是检测 npm 包的 latest 版本，并与本地的 npm 包版本比对，如果有更新则下载新版本的 npm 包并载入数据。

之前我是假设 npm 包版本符合 semver 的，所以使用了 `semver` 包来比对版本，然而对于刚才的数据修复发的 `2018.1.18-1`，比较尴尬的是 `semver` 不能够得出 `2018.1.18-1` 比 `2018.1.18` 版本高的判断

```
require('semver').gt('2018.1.18-1', '2018.1.18')
false
```

因此，我想确认一下数据库 npm 包版本的命名方式是有符合 semver 的打算。比如如果兼容 semver 的比较函数，命名为 yyyy.m.d-x 更好，即 2018.1.18-0, 2018.1.18-1 这样

**Comment by KagamiChan** [comment]
内部讨论了一下，改成检测到 latest 版本与已安装版本不一致则下载 latest 版本了 - -

**Comment by Diablohu** [comment]
那么，在维持“年.月.日”版本号的前提下，像这种临时修正的版本，符合semver规则有啥好的建议么？

**Comment by KagamiChan** [comment]
感觉像 caniuse-db 那样的思路命名为 1.0. yyyymmdd 可能是最好的，但是需要从第一个版本开始就这样做

可以命名为 yyyy.m.d-x 这样的，第一个版本的 x 是 0，之后修正的话就是 1，以此类推
虽然这个也不算 semver，但是 `node-semver` 的 gt / lt 之类能够比较这样的版本号，虽然没有具体测试过，但 yarn upgrade 和 npm update 应该也能够正确地比较这个

**Comment by Diablohu** [comment]
semver 调整，现在新的规则是 `YYYYMMDD.X.Y`
