### ISSUE TITLE
希望Wiki页能增加所有数据库的属性介绍

### ISSUE THREAD

**Issue by boholder** [TeamFleet/WhoCallsTheFleet-DB#9]
是这样，我想做一个rest api server，用json格式分享舰c的数据。
会用到本项目的`ship`,`item`以及相关关系库。

前后翻了翻db文件，大概弄懂了各库关系...
但对于部分属性（比如各库好像都有`illust_extra`和`illu_version`，
没搜到是不是Mongodb的系统自建属性，还有就是`ship_classes.speed_rule`之类）
还是没能理解含义，
希望您能补上属性介绍。

另外我未经您同意修改了Wiki页的ship页面...补足了英翻和格式化，
但也留下了三个属性含义没解释（`class`,`illust_extra`,`illu_version`），
希望您不要介意...

再另外，好像部分数据不完善？
比如ship_classes里长门级缺失英语名（罗马音），还有好像您还想把台词也加进去但没完成？
要不要做个简单的表单网页然后发动玩家来提交？

**Comment by Diablohu** [comment]
- `ship.illust_extra` 限定图鉴ID，对应 `exillusts.nedb`，后者对应 https://github.com/TeamFleet/WhoCallsTheFleet-Pics
- `ship.illust_version` 游戏官方 API 中对应的图鉴版本，每次有图鉴修改时会累加，包括从限定图鉴换回到常规图鉴
- 罗马音、英文名有很多缺失，主要是自己这边暂时没有用到，另外自己这边的程序也有一些逻辑上的处理：
  - 单独的舰娘名称，如果缺失英文名，会尝试使用罗马音名，并将首字母大写
  - 如果也缺失罗马音，会尝试使用前一个改造版本对应的名字
- 有关 `speed_rule`
  - 如果单独的舰娘有设定，会采用该值
  - 如果没有，会采用所属舰级（class）的该值
  - 计算规则：https://github.com/TeamFleet/KCKit/blob/master/src/calculate/ship/speed.js

**Comment by boholder** [comment]
啊，解答的很清楚明了，太感谢了。
